export const dataMockInfo = [
    {
      id: 1001,
      client_name: "Sofia Salinas",
      client_email: "sofia@example.com",
      client_phone: "+573145678901",
      client_dni: "1089345678",
      client_address: "Calle 123, Bogotá",
      invoice_image: "",
      id_image: "",
      package: "Student Adventure",
      quoted_flight: "Bogotá - Toulouse",
      agency_cost: 950,
      amount: 1250,
      transaction_type: "abono",
      status: "approved",
      seller_id: 101,
      seller_name: "John Seller",
      receipt: "",
      start_date: "2025-08-12",
      end_date: "2025-08-20",
      travelers: []
    },
    {
      id: 1002,
      client_name: "Daniel Rivera",
      client_email: "daniel@example.com",
      client_phone: "+573156789012",
      client_dni: "1089456789",
      client_address: "Carrera 45, Medellín",
      invoice_image: "",
      id_image: "",
      package: "París Tour Package",
      quoted_flight: "Bogotá - París",
      agency_cost: 1000,
      amount: 1200,
      transaction_type: "abono",
      status: "pending",
      seller_id: 102,
      seller_name: "John Seller",
      receipt: "",
      start_date: "2025-07-15",
      end_date: "2025-07-25",
      travelers: []
    },
    {
      id: 1003,
      client_name: "Miguel Muñoz",
      client_email: "miguel@example.com",
      client_phone: "+573167890123",
      client_dni: "1089567890",
      client_address: "Avenida 67, Cali",
      invoice_image: "",
      id_image: "",
      package: "Barcelona Tour",
      quoted_flight: "Bogotá - Barcelona",
      agency_cost: 800,
      amount: 850,
      transaction_type: "abono",
      status: "rejected",
      seller_id: 101,
      seller_name: "Admin User",
      receipt: "",
      start_date: "2025-08-10",
      end_date: "2025-08-20",
      travelers: []
    }
  ];